name: tubes_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.5
  http: ^0.13.6
  fluttertoast: ^8.0.7
  shared_preferences: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_swiper: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
